1.

a)
CREATE TABLE SPORTISTA (

	ID NUMBER(5),
	IME VARCHAR(10) NOT NULL,
	PREZIME VARCHAR(20) NOT NULL,
	BRTEL NUMBER(9),
	GODINA_RODJ NUMBER(4) NOT NULL,
	GRAD VARCHAR(15) NOT NULL,
	PLATA NUMBER,
	CONSTRAINT SPORTISTA_PK PRIMARY KEY (ID)
);

CREATE TABLE KLUB(

	ID NUMBER(5),
	NAZIV VARCHAR(20) NOT NULL,
	LOKACIJA VARCHAR(40) NOT NULL,
	GOD_OSNIVANJA NUMBER(4),
	SPORT VARCHAR(18),
	CONSTRAINT KLUB_PK PRIMARY KEY (ID)
);

CREATE TABLE CLAN(

	ID NUMBER(5),
	ID_SPORTISTE NUMBER(5),
	ID_KLUBA NUMBER(5),
	DATUM_OD DATE NOT NULL,
	DATUM_DO DATE DEFAULT NULL,
	TIM VARCHAR(5),
	CONSTRAINT CLAN_PK PRIMARY KEY(ID,ID_KLUBA,ID_SPORTISTE),
	CONSTRAINT CLAN_SPORT FOREIGN KEY (ID_SPORTISTE) REFERENCES SPORTISTA(ID),
	CONSTRAINT CLAN_KLUB FOREIGN KEY (ID_KLUBA) REFERENCES KLUB(ID),
	CONSTRAINT TIM_CK CHECK (TIM IN ('skola','prvi','mladi'))
);

b)
	SELECT KLUB.NAZIV||'-'||KLUB.LOKACIJA AS NAZIV_I_LOKACIJA,KLUB.GOD_OSNIVANJA
	FROM KLUB
	WHERE EXTRACT(YEAR FROM SYSDATE)-KLUB.GOD_OSNIVANJA>20 AND KLUB.SPORT='odbojka'
	ORDER BY KLUB.GOD_OSNIVANJA DESC

c)
	SELECT SPORTISTA.IME,SPORTISTA.PREZIME,CLAN.TIM
	FROM SPORTISTA INNER JOIN CLAN ON SPORTISTA.ID=CLAN.ID_SPORTISTE
	INNER JOIN KLUB ON CLAN.ID_KLUBA=KLUB.ID
	WHERE EXTRACT(YEAR FROM SYSDATE)-SPORTISTA.GODINA_RODJ<30 AND SPORTISTA.GRAD != KLUB.LOKACIJA AND CLAN.DATUM_DO IS NULL

d)
	SELECT *
	FROM(SELECT KLUB.NAZIV,KLUB.SPORT,COUNT(CLAN.ID)AS BROJ_CLANOVA
	FROM KLUB
	INNER JOIN CLAN ON KLUB.ID = CLAN.ID_KLUBA
	INNER JOIN SPORTISTA ON CLAN.ID_SPORTISTE=SPORTISTA.ID
	WHERE KLUB.TIM='skola'
	AND EXTRACT(YEAR FROM SYSDATE)-CLAN.GODINA_RODJ <15
	GROUP BY KLUB.ID
	ORDER BY BROJ_CLANOVA DESC)
	WHERE ROWNUM=1

e)
	SELECT KLUB.NAZIV,KLUB.LOKACIJA 
	FROM KLUB
	INNER JOIN CLAN ON KLUB.ID = CLAN.ID_KLUBA
	INNER JOIN SPORTISTA ON CLAN.ID_SPORTISTE=SPORTISTA.ID
	GROUP BY KLUB.NAZIV,KLUB.LOKACIJA 
	HAVING COUNT(SELECT KLUB.ID FROM KLUB INNER JOIN CLAN ON KLUB.ID = CLAN.ID_KLUBA
	INNER JOIN SPORTISTA ON CLAN.ID_SPORTISTE=SPORTISTA.ID 
	WHERE CLAN.TIM='mladi' AND CLAN.PLATA > (SELECT AVG(PLATA) FROM SPORTISTA INNER JOIN CLAN ON SPORTISTA.ID = CLAN.ID_SPORTISTE
	WHERE SUM(CASE WHEN CLAN.GRAD='NOVI SAD' AND CLAN.PLATA>20000 THEN 1 ELSE 0)=0))>=2 //VEROVATNO NIJE TACNO OVO :(

2.
a)
	CREATE VIEW IGRAC_STAT 
	AS 
	SELECT SPORTISTA.IME,SPORTISTA.PREZIME,EXTRACT(YEAR FROM SYSDATE)-SPORTISTA.GODINA_RODJ AS STAROST , COUNT (DESTINCT CLAN.ID_KLUBA) AS BROJ_KLUBOVA
	FROM SPORTISTA
	INNER JOIN CLAN ON SPORTISTA.ID = CLAN.ID_SPORTISTE
	INNER JOIN KLUB ON CLAN.ID_KLUBA=KLUB.ID 
	GROUP BY SPORTISTA.IME,SPORTISTA.PREZIME,SPORTISTA.GODINA_RODJ


	SELECT *
	FROM IGRAC_STAT 
	WHERE BROJ_KLUBOVA >= 2

b)
	UPDATE SPORTISTA 
	SET SPORTISTA.PLATA = SPORTISTA.PLATA * 0.97
	WHERE SPORTISTA.ID IN (SELECT SPORTISTA.ID FROM SPORTISTA INNER JOIN CLAN ON SPORTISTA.ID = CLAN.ID_SPORTISTE INNER JOIN
	KLUB ON CLAN.ID = KLUB.ID_KLUBA WHERE KLUB.SPORT='odbojka'AND KLUB.LOKACIJA='Novi Sad' AND CLAN.TIM='prvi')

c)
	DELETE FROM CLAN
    WHERE ID_SPORTISTE IN (
    SELECT SPORTISTA.ID
    FROM SPORTISTA
    INNER JOIN CLAN ON SPORTISTA.ID = CLAN.ID_SPORTISTE
    INNER JOIN KLUB ON CLAN.ID_KLUBA = KLUB.ID
    WHERE CLAN.TIM = 'skola'
    AND EXTRACT(YEAR FROM SYSDATE) - KLUB.GOD_OSNOVANJA > 20
    AND SPORTISTA.ID NOT IN (
        SELECT SPORTISTA.ID
        FROM SPORTISTA
        INNER JOIN CLAN ON SPORTISTA.ID = CLAN.ID_SPORTISTE
        WHERE CLAN.TIM = 'mladi'
    )
);







