1.

a)
CREATE TABLE KOMPANIJA(

	PIB NUMBER(5)
	NAZIV VARCHAR2(20) NOT NULL
	ULICA VARCHAR2(20)
	BROJ INT
	GRAD VARCHAR(15)
	DRZAVA VARCHAR(14)
	CONSTRAINT KOMPANIJA_PK PRIMARY KEY (PIB)
);
CREATE TABLE ZAPOSLENI (

	JMBG NUMBER(13)
	DATUM_RODJ DATE
	IME VARCHAR2(13) NOT NULL
	PREZIME VARCHAR2(20) NOT NULL
	SSLOVO CHAR(1)
	RADNI_STAZ NUMBER(2)
	PLATA REAL NOT NULL
	CONSTRAINT ZAPOSLENI_PK PRIMARY KEY (JBMG)
);
CREATE TABLE VOZILO(
	ID NUMBER(5)
	KILOMETRAZA REAL
	GODINA_PROIZ NUMBER(4) 
	DATUM_ISTEKA DATE
	TIP_GORIVO VARCHAR2(6)
	PIBFIR NUMBER(5)
	CONSTRAINT VOZILO_PK PRIMARY KEY (ID)
	CONSTRAINT VOZILO_FK FOREIGN KEY (PIBFIR) REFERENCES KOMPANIJA(PIB)
	CONSTRAINT TIP_CK CHECK (TIP_GORIVO IN ('DIZEL','BENZIN'))

);
CREATE TABLE PRATI(
	 DATUM_POC DATE
	 DAT_KRAJA DATE
	 JMBG NUMBER(13) 
	 IDVOZILA NUMBER(5)
	 CONSTRAINT PRATI_PK PRIMARY KEY (JMBG,IDVOZILA)
	 CONSTRAINT PRATI_ZAPOSLENI_FK FOREIGN KEY (JMBG) REFERENCES ZAPOSLENI(JMBG)
	 CONSTRAINT PRATI_VOZILO_FK FOREIGN KEY (IDVOZILA) REFERENCES VOZILO(ID)

);

b)
	SELECT KOMPANIJA.NAZIV,KOMPANIJA.DRZAVA,SUM(VOZILO.KILOMETRAZA)AS UKUPNA_KILOMETRAZA
	FROM KOMPANIJA
	INNER JOIN VOZILO ON KOMPANIJA.PIB = VOZILO.PIBFIR
	GROUP BY KOMPANIJA.PIB,KOMPANIJA.NAZIV,KOMPANIJA.DRZAVA
	HAVING COUNT(VOZILO.ID)>=2
	ORDER BY KOMPANIJA.NAZIV

c)
	SELECT ZAPOSLENI.JMBG,ZAPOSLENI.IME,ZAPOSLENI.SSLOVO,ZAPOSLE.PREZIME
	FROM ZAPOSLENI
	WHERE ZAPOSLENI.JMBG IN (SELECT ZAPOSLENI.JMBG FROM ZAPOSLENI
	INNER JOIN PRATI ON ZAPOSLENI.JMBG=PRATI.JMBG
	INNER JOIN VOZILO ON PRATI.IDVOZILA=VOZILO.ID
	INNER JOIN KOMPANIJA ON VOZILO.PIBFIR = KOMPANIJA.PIB
	GROUP BY ZAPOSLENI.JMBG,ZAPOSLENI.IME,ZAPOSLENI.SSLOVO,ZAPOSLE.PREZIME
	HAVING  COUNT(KOMPANIJA.PIB)<5 
	AND SUM(CASE WHEN VOZILO.TIP='DIZEL' THEN 1 ELSE 0 END)=0 
	AND SUM(CASE WHEN VOZILO.KILOMETRAZA>100000 THEN 1 ELSE 0 END)=0)

d)
	SELECT KOMPANIJA.NAZIV,COUNT(PRATI.IDVOZILA) AS BROJ_PRACENIH
	FROM KOMPANIJA
	INNER JOIN VOZILO ON KOMPANIJA.PIB = VOZILO.PIBFIR
	INNER JOIN PRATI ON VOZILO.ID=PRATI.IDVOZILA
	WHERE PRATI.DAT_KRAJA IS NULL AND PRATI.DAT_POC IS NOT NULL
	GROUP BY KOMPANIJA.NAZIV
	ORDER BY BROJ_PRACENIH ASC 
	LIMIT 1

2.
 a)
	CREATE VIEW STATISTIKA
	AS
	SELECT VOZILO.ID,VOZILO.KILOMETRAZA,VOZILO.GODINA_PROIZ,KOMPANIJA.NAZIV,SUM(DATEDIFF(SYSDATE,PRATI.DATUM_POC)) AS DANI_PRACENJA,COUNT(ZAPOSLENI.JMBG) AS BROJ_ZAP
	FROM VOZILO
	INNER JOIN PRATI ON VOZILO.ID = PRATI.IDVOZILA
	INNER JOIN KOMPANIJA ON VOZILO.PIBFIR = KOMPANIJA.PIB
	INNER JOIN ZAPOSLENI ON PRATI.JMBG = ZAPOSLENI.JMBG
	WHERE YEAR(SYSDATE)-VOZILO.GODINA_PROIZ>7
	GROUP BY VOZILO.ID,VOZILO.KILOMETRAZA,KOMPANIJA.NAZIV

	SELECT * FROM STATISTIKA
	HAVING BROJ_ZAP >=3 

b)
	UPDATE ZAPOSLENI
	SET PLATA = PLATA*1.20
	WHERE ZAPOSLENI.PLATA <(SELECT AVG(PLATA) FROM  ZAPOSLENI)
	AND ZAPOSLENI.JMBG IN (SELECT ZAPOSLENI.JMBG FROM ZAPOSLENI INNER JOIN PRATI ON ZAPOSLENI.JMBG = PRATI.JMBG
	INNER JOIN VOZILO ON PRATI.IDVOZILA=VOZILO.ID INNER JOIN KOMPANIJA ON VOZILO.PIBFIR = KOMPANIJA.PIB
	WHERE KOMPANIJA.GRAD='BEOGRAD' 
	GROUP BY ZAPOSLENI.JMBG,ZAPOSLENI.IME,ZAPOSLENI.PREZIME
	HAVING COUNT(DISTINCT VOZILO.ID )>=2)

c)
	DELETE FROM PRATI
	WHERE PRATI.DAT_KRAJA-PRATI.DAT_POC<3 AND PRATI.IDVOZILA IN (SELECT VOZILO.ID FROM VOZILO
	INNER JOIN KOMPANIJA ON VOZILO.PIBFIR=KOMPANIJA.PIB 
	WHERE KOMPANIJA.PIB IN (SELECT KOMPANIJA.PIB FROM KOMPANIJA
		INNER JOIN VOZILO ON KOMPANIJA.PIB=VOZILO.PIBFIR 
		WHERE VOZILO.TIP='DIZEL'
		GROUP BY KOMPANIJA.PIB
		HAVING COUNT (DISTINCT VOZILO.ID)>5)
	)
	AND PRATI.JMBG IN (SELECT ZAPOSLENI.JMBG FROM ZAPOSLENI WHERE ZAPOSLENI.RADNI_STAZ>15)


