
1.

a)
CREATE TABLE ATLETICAR(

	ID NUMBER(5),
	IME VARCHAR(10) NOT NULL,
	PREZIME VARCHAR(20) NOT NULL,
	NAPOMENA VARCHAR(50),
	POL CHAR(1) NOT NULL,
	GODINA_RODJ NUMBER(4),
	CONSTRAINT ATLETICAR_PK PRIMARY KEY (ID),
	CONSTRAINT GODINA_RODJ_CK CHECK (GODINA_RODJ>1985 AND GODINA_RODJ < 2007),
	CONSTRAINT POL_CK CHECK (POL IN ('M','Z'))
);

CREATE TABLE TAKMICENJE(

	ID NUMBER(5),
	DATUM DATE,
	NAZIV VARCHAR(30) NOT NULL,
	DUZINA INT,
	CONSTRAINT TAKMICENJE_PK PRIMARY KEY (ID)
);

CREATE TABLE ATLETICAR_TAKMICENJE (

	ATLETICAR_ID NUMBER(5),
	TAKMICENJE_ID NUMBER(5),
	CONSTRAINT ATLETICAR_FK FOREIGN KEY (ATLETICAR_ID) REFERENCES ATLETICAR(ID),
	CONSTRAINT TAKMICENJE_FK FOREIGN KEY (TAKMICENJE_ID) REFERENCES TAKMICENJE (ID),
	CONSTRAINT ATLETICAR_TAKMICENJE_PK PRIMARY KEY (ATLETICAR_ID,TAKMICENJE_ID)
);

b)
SELECT TAKMICENJE.NAZIV,ATLETICAR.POL,COUNT(ATLETICAR.ID) AS BROJ_PO_POLU
FROM TAKMICENJE
INNER JOIN ATLETICAR_TAKMICENJE ON TAKMICENJE.ID = ATLETICAR_TAKMICENJE.TAKMICENJE_ID
INNER JOIN ATLETICAR ON ATLETICAR_TAKMICENJE.ATLETICAR_ID=ATLETICAR.ID 
GROUP BY TAKMICENJE.NAZIV,ATLETICAR.POL
HAVING ATLETICAR.POL='Z' AND COUNT(ATLETICAR.ID) > 10

c)
SELECT ATLETICAR.ID,ATLETICAR.IME,ATLETICAR.PREZIME,ATLETICAR.POL,ATLETICAR.GODINA_RODJ,COUNT(TAKMICENJE.ID) AS BROJ_TAKMICENJA
FROM ATLETICAR
INNER JOIN ATLETICAR_TAKMICENJE ON ATLETICAR.ID = ATLETICAR_TAKMICENJE.ATLETICAR_ID
INNER JOIN TAKMICENJE ON ATLETICAR_TAKMICENJE.TAKMICENJE_ID = TAKMICENJE.ID
GROUP BY ATLETICAR.ID,ATLETICAR.IME,ATLETICAR.PREZIME,ATLETICAR.POL,ATLETICAR.GODINA_RODJ
HAVING COUNT(TAKMICENJE.ID)>4 AND SUM(CASE WHEN TAKMICENJE.DUZINA <1000 THEN 1 ELSE 0 END)=0	

d)
SELECT TAKMICENJE.NAZIV,COUNT(ATLETICAR.ID) AS BROJ_TAKMICARA
FROM TAKMICENJE 
INNER JOIN ATLETICAR_TAKMICENJE ON TAKMICENJE.ID = ATLETICAR_TAKMICENJE.TAKMICENJE_ID
INNER JOIN ATLETICAR ON ATLETICAR_TAKMICENJE.ATLETICAR_ID = ATLETICAR.ID 
GROUP BY TAKMICENJE.NAZIV
ORDER BY BROJ_TAKMICARA ASC 
LIMIT 1

2.

a)
CREATE VIEW INFORMACIJE
AS
SELECT TAKMICENJE.NAZIV,TAKMICENJE.DATUM,COUNT(ATLETICAR.ID) AS BROJ_TAKMICARA , AVG(YEAR(SYSDATE)-ATELTICAR.GODINA_RODJ) AS PROSECNA STAROST
FROM TAKMICENJE 
INNER JOIN ATLETICAR_TAKMICENJE ON TAKMICENJE.ID = ATLETICAR_TAKMICENJE.TAKMICENJE_ID
INNER JOIN ATLETICAR ON ATLETICAR_TAKMICENJE.ATLETICAR_ID = ATLETICAR.ID 
GROUP BY TAKMICENJE.ID,TAKMICENJE.NAZIV,TAKMICENJE.DATUM;

SELECT * 
FROM INFORMACIJE
ORDER BY BROJ_TAKMICARA DESC
LIMIT 1;

b)
UPDATE ATLETICAR
SET ATLETICAR.NAPOMENA='SENIOR'
WHERE ATLETICAR.ID IN(
SELECT ATLETICAR.ID 
FROM ATLETICAR
INNER JOIN ATLETICAR_TAKMICENJE ON ATLETICAR.ID=ATLETICAR_TAKMICENJE.ATLETICAR_ID
INNER JOIN TAKMICENJE ON ATLETICAR_TAKMICENJE.TAKMICENJE_ID=TAKMICENJE.ID 
WHERE YEAR(SYSDATE)-ATLETICAR.GODINA_RODJ>18
GROUP BY ATLETICAR.ID 
HAVING SUM(CASE WHEN TAKMICENJE.DUZINA=400 THEN 1 ELSE 0 END)=0 
AND SUM(CASE WHEN TAKMICENJE.DUZINA>1500 THEN 1  ELSE 0 END)>=3
);

c)
DELETE FROM TAKMICENJE
WHERE TAKMICENJE.ID IN (SELECT TAKMICENJE.ID FROM TAKMICENJE
INNER JOIN ATLETICAR_TAKMICENJE ON TAKMICENJE.ID=ATLETICAR_TAKMICENJE.TAKMICENJE_ID
INNER JOIN ATLETICAR ON ATLETICAR_TAKMICENJE.ATLETICAR_ID=ATLETICAR.ID
WHERE SYSDATE-TAKMICENJE.DATUM <10 AND UPPER(TAKMICENJE.NAZIV)LIKE '%OPEN%'
GROUP BY TAKMICENJE.ID 
HAVING COUNT(ATLETICAR.ID)<20)