1.

a)
CREATE TABLE POSLASTICAR(
		
	ID NUMBER(5),
	IME VARCHAR(9) NOT NULL,
	PREZIME VARCHAR(20) NOT NULL,
	RADNISTAZ INT,
	POL CHAR(1) NOT NULL,
	SPECIJALNOST VARCHAR(30),
	CONSTRAINT POSLASTICAR_PK PRIMARY KEY (ID),
	CONSTRAINT POL_CK CHECK (POL IN ('M','Z')),
	CONSTRAINT SPECIJALNOST_CK CHECK (SPECIJALNOST IN ('sitni_kolaci','domace_torte','ostalo'))
);
CREATE TABLE POSLASTICA (
 
	ID NUMBER(5),
	NAZIV VARCHAR(20) NOT NULL,
	GRAMAZA REAL,
	TIP VARCHAR(5),
	BROJ_KALORIJA REAL,
	VEGANSKO NUMBER(1) NOT NULL,
	CONSTRAINT POSLASTICA_PK PRIMARY KEY (ID),
	CONSTRAINT TIP_CK CHECK (TIP IN('torta','kolac')),
	CONSTRAINT GRAMAZA_CK CHECK (GRAMAZA>0),
	CONSTRAINT VEGANSKO_CK CHECK (VEGANSKO IN (1,0))
);

CREATE TABLE KUPAC (

	ID NUMBER(5),
	IME VARCHAR(12) NOT NULL,
	PREZIME VARCHAR(20) NOT NULL,
	ADRESA VARCHAR (40) NOT NULL,
	CONSTRAINT KUPAC_PK PRIMARY KEY (ID)
);

CREATE TABLE NARUDZBINA (

  ID NUMBER(5),
  POSLASTICAR NUMBER(5),
  POSLASTICA NUMBER(5),
  CENA REAL NOT NULL,
  DATUM DATE,
  ADRESA VARCHAR(40) NOT NULL,
  OCENA INT DEFAULT 0,
  CONSTRAINT NARUDZBINA_PK PRIMARY KEY (ID),
  CONSTRAINT NARUDZBINA_TICAR_FK FOREIGN KEY(POSLASTICAR) REFERENCES POSLASTICAR(ID),
  CONSTRAINT NARUDZBINA_TICA_FK FOREIGN KEY (POSLASTICA) REFERENCES POSLASTICA(ID),
  CONSTRAINT OCENA_CK CHECK (OCENA >=0 AND OCENA <= 5)
);

b)
SELECT POSLASTICA.NAZIV,POSLASTICA.TIP,(POSLASTICA.GRAMAZA),COUNT(*) AS PONAVLJANJE
FROM POSLASTICA INNER JOIN NARUDZBINA ON POSLASTICA.ID = NARUDZBINA.POSLASTICA
GROUP BY POSLASTICA.TIP,POSLASTICA.NAZIV,POSLASTICA.GRAMAZA 
HAVING YEAR(NARUDZBINA.DATUM) > 2023
ORDER BY PONAVLJANJE DESC

c)
SELECT KUPAC.IME,KUPAC.PREZIME , COUNT(*) AS BROJ_POSLASTICA
FROM KUPAC INNER JOIN NARUDZBINA ON KUPAC.ADRESA=NARUDZBINA.ADRESA 
INNER JOIN POSLASTICA ON NARUDZBINA.POSLASTICA=POSLASTICA.ID
WHERE POSLASTICA.BROJ_KALORIJA<150 AND POSLASTICA.VEGANSKO =0 AND UPPER(KUPAC.ADRESA) LIKE '%BEOGRAD%'
GROUP BY KUPAC.IME , KUPAC.PREZIME
HAVING COUNT(*)>=3

d)
SELECT POSLASTICAR.IME,POSLASTICAR.PREZIME,POSLASTICAR.POL,POSLASTICAR.RADNISTAZ,COUNT(*) AS VEGANCOUNT 
FROM POSLASTICAR 
INNER JOIN NARUDZBINA ON POSLASTICAR.ID = NARUDZBINA.POSLASTICAR
INNER JOIN KUPAC ON NARUDZBINA.ADRESA = KUPAC.ADRESA
INNER JOIN POSLASTICA ON NARUDZBINA.POSLASTICA = POSLASTICA.ID
WHERE POSLASTICAR.SPECIJALNOST='domace_torte'AND UPPER(KUPAC.ADRESA) LIKE '%NIS%' AND POSLASTICA.VEGANSKO=1
GROUP BY POSLASTICAR.IME,POSLASTICAR.PREZIME,POSLASTICAR.POL,POSLASTICAR.RADNISTAZ
ORDER BY VEGANCOUNT DESC
LIMIT 1 


2. 

a)
CREATE VIEW STATISTIKA
AS
SELECT POSLASTICAR.IME , POSLASTICAR.PREZIME , COUNT(NARUDZBINA.ID) AS UKUPNO_NARUDZBINA , POSLASTICA.TIP,AVG(NARUDZBINA.OCENA)AS PROSECNA_OCENA,AVG(NARUDZBINA.CENA)AS PROSECNA_CENA 
FROM POSLASTICAR 
INNER JOIN NARUDZBINA ON POSLASTICAR.ID=NARUDZBINA.POSLASTICAR
INNER JOIN POSLASTICA ON NARUDZBINA.POSLASTICA=POSLASTICA.ID
GROUP BY POSLASTICAR.IME , POSLASTICAR.PREZIME,POSLASTICA.TIP 

SELECT POSLASTICAR.IME,POSLASTICAR.PREZIME,UKUPNO_NARUDZBINA
FROM STATISTIKA
WHERE POSLASTICA.TIP='kolac'
ORDER BY UKUPNO_NARUDZBINA DESC
LIMIT 1

b)
UPDATE NARUDZBINA
SET NARUDBINA.CENA= NRAUDBINA.CENA*0.95
WHERE NARUDZBINA.ADRESA IN (
	SELECT NARUDZBINA.ADRESA
	FROM NARUDZBINA  
	INNER JOIN POSLASTICA ON NARUDBINA.POSLASTICA=POSLASTICA.ID
	WHERE NARUDZBINA.OCENA=0 AND POSLASTICA.TIP='TORTA' 
	GROUP BY NARUDZBINA.ADRESA
	HAVING COUNT(*) >=2 
)

c)
	DELETE FROM POSLASTICAR
	INNER JOIN NARUDZBINA ON POSLASTICAR.ID=NARUDZBINA.POSLASTICAR
	GROUP BY NARUDZBINA.OCENA
	HAVING NARUDZBINA.OCENA >0 AND NARUDZBINA.OCENA<5



